### ISSUE TITLE
Cannot run any commands which depend on synthesisr

### ISSUE THREAD

**Issue by GitNoise** [elizagrames/litsearchr#28]
Every command which is dependent on synthesisr fail. 

For instance, running `naiveresults <- litsearchr::remove_duplicates(naiveimport, field = "title", method = "stringdist")` results in:

```
 Error in synthesisr::find_duplicates(data = df, match_variable = field,  : 
  unused argument (match_variable = field)
```

I am trying to follow the tutorial / example at https://elizagrames.github.io/litsearchr/litsearchr_vignette_v030.html.

I installed litsearcher like this: 
```
To install litsearchr use devtools::install_github("elizagrames/litsearchr") 
in R or RStudio. You may need to install the devtools package if it is not 
already installed. This will also install all the litsearchr dependencies.
```

**Comment by elizagrames** [comment]
I'll look into it; synthesisr should have been installed automatically since it is a dependency but I must have misspecified it somewhere.

In the meantime: `devtools::install_github("rmetaverse/synthesisr")` will solve the problem.

**Comment by kravitz-eli** [comment]
@elizagrames 

I am happy to help narrow down issues and debug. It would be helpful if you let us known which version of synthesir you're using, so I can install that version. 

`packageVersion("synthesisr")`
> ‘0.2.0’

**Comment by portitor** [comment]
Hi,
synthesisr 0.2.0 has changed some functions, not only in the implementation but also in the parameters specification. Currently, `litsearchr::remove_duplicates` calls `synthesisr::find_duplicates` with the wrong parameters, since the latest version of `synthesisr::find_duplicates` does not accept `match_variable` as a parameter. To overcome this problem, I used `synthesisr::deduplicate` directly. This allows finding and removing duplicates in a dataset, all in one go. I believe that `litsearchr::remove_duplicates` could be easily updated by making it call `synthesisr::deduplicate` directly. Hope this helps...

**Comment by GitNoise** [comment]
Maybe using dependency management tool would solve these issues.. I've seen multiple issues here before which seem to be dependent on version changes.
Have a look at this: https://blog.learningtree.com/manage-packages-in-r-how/

**Comment by GitNoise** [comment]
My version is:
> packageVersion("synthesisr")
[1] ‘0.2.0’

**Comment by kravitz-eli** [comment]
> Maybe using dependency management tool would solve these issues

Or just rewriting the functions that depend on synthesisr to get rid of the dependence. Litsearchr and synthesisr look like they're being developed independently. These issues will keep coming up.

 @elizagrames could ask the synthesisr to merge projects or ask to (more-or-less) copy-paste their code into litsearchr.

**Comment by elizagrames** [comment]
So the long story short is that I write the code for both litsearchr and synthesisr and have somehow royally screwed things up. I moved the basic importing and deduplication code to synthesisr but retained wrapper functions in litsearchr because of descriptions in the published paper for litsearchr. When Martin updated the synthesisr dedupe functions, this broke litsearchr calls to it. I will sort out the discrepancies between packages ASAP.

**Comment by Otoliths** [comment]
Hi：
Suggest modifications to the original _remove_duplicates_ function:

remove_duplicates <- function (df,field, method = c("stringdist", "fuzzdist", "exact")) 
{
  df <- synthesisr::deduplicate(data=df, match_by=field, match_function = method)
  return(df)
}

**Comment by elizagrames** [comment]
This is now fixed exactly as suggested.
