### ISSUE TITLE
rapidraker not available for R version 3.6.1

### ISSUE THREAD

**Issue by simone-mordue** [elizagrames/litsearchr#29]
Hello, 

I am having trouble following the vignette. Unfortunately I cannot use the 'RAKE' function as I am not able to install 'rapidraker'. Please could you advise how to work around this issue?

Many thanks,
Simone

**Comment by elizagrames** [comment]
Which version of the vignette/package are you using? The most recent vignette should default to fakerake, which is an alternative implementation of the approach used by rapidraker. You should be able to just change `method="RAKE"` to `method="fakerake"` to avoid the issue, though you may run into a few more if you have an old version of the vignette since some of the default settings have changed.

Related to the rapidraker dependency issue (if anyone else has the same issue), a lot of people have problems installing it, usually associated with rJava issues. I dropped the dependency though because of this and replaced it with fakerake.

**Comment by simone-mordue** [comment]
Dear Eliza,

Thank you for your quick reply. ‘fakerake’ works well.

Best wishes,
Simone

On 3 Feb 2020, at 13:52, Eliza Grames <notifications@github.com> wrote:

﻿

Which version of the vignette/package are you using? The most recent vignette should default to fakerake, which is an alternative implementation of the approach used by rapidraker. You should be able to just change method="RAKE" to method="fakerake" to avoid the issue, though you may run into a few more if you have an old version of the vignette since some of the default settings have changed.

Related to the rapidraker dependency issue (if anyone else has the same issue), a lot of people have problems installing it, usually associated with rJava issues. I dropped the dependency though because of this and replaced it with fakerake.
